name: Build and Release (Swift - Rootless Only)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Install dependencies
        run: |
          brew install ldid
          brew install make
          brew install automake
          brew install autoconf
          brew install libtool
          brew install pkg-config
          brew install wget
          brew install jq
          brew install dpkg

      - name: Download Spotify IPA
        run: |
          wget --content-disposition -q "${{ secrets.SPOTIFY_IPA_URL }}"
          SPOTIFY_PACKAGE=$(ls *.ipa | head -n 1)
          if [ -z "$SPOTIFY_PACKAGE" ]; then
            echo "Error: Spotify IPA was not downloaded!"
            exit 1
          fi

          echo "SPOTIFY_PACKAGE=$SPOTIFY_PACKAGE" >> $GITHUB_ENV
          SPOTIFY_VERSION="${SPOTIFY_PACKAGE%.ipa}"
          echo "SPOTIFY_VERSION=$SPOTIFY_VERSION" >> $GITHUB_ENV
        shell: /bin/zsh {0}
        env:
          SWIFTPROTOBUF_VERSION: 1.29.0
          EEVEESPOTIFY_ROOTLESS: com.eevee.spotify_6.1_iphoneos-arm64.deb
          EEVEESPOTIFY_VERSION: 6.1
          SWIFTPROTOBUF_ROOTLESS: org.swift.protobuf.swiftprotobuf_1.29.0_iphoneos-arm64.deb
          OPENSPOTIFYSAFARIEXTENSION: OpenSpotifySafariExtension/OpenSpotifySafariExtension.appex

      - name: Build project
        run: |
          make clean
          make

      - name: Inject tweaks (Rootless)
        run: |
          EEVEESPOTIFY_PACKAGE_ROOTLESS="EeveeSpotify-${EEVEESPOTIFY_VERSION}-${SPOTIFY_VERSION}-rootless.ipa"
          echo "EEVEESPOTIFY_PACKAGE_ROOTLESS=$EEVEESPOTIFY_PACKAGE_ROOTLESS" >> $GITHUB_ENV

          ./ivinject/ivinject-arm64 "$SPOTIFY_PACKAGE" "$EEVEESPOTIFY_PACKAGE_ROOTLESS" \
            -i "$EEVEESPOTIFY_ROOTLESS" -i "$SWIFTPROTOBUF_ROOTLESS"

      - name: Package Safari Extension
        run: |
          if [ -d "$OPENSPOTIFYSAFARIEXTENSION" ]; then
            zip -r OpenSpotifySafariExtension.zip "$OPENSPOTIFYSAFARIEXTENSION"
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: EeveeSpotify
          path: |
            ${{ env.EEVEESPOTIFY_PACKAGE_ROOTLESS }}
            OpenSpotifySafariExtension.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ env.EEVEESPOTIFY_VERSION }}-${{ env.SPOTIFY_VERSION }}"
          name: "EeveeSpotify v${{ env.EEVEESPOTIFY_VERSION }}-${{ env.SPOTIFY_VERSION }}"
          files: |
            ${{ env.EEVEESPOTIFY_PACKAGE_ROOTLESS }}
            OpenSpotifySafariExtension.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
